services:
  frontend:
    build:
      context: frontend
    ports:
      - "8100:80"
    volumes:
      - ./config.js.example:/usr/share/nginx/html/config.js

  backend:
    build:
      context: .
    env_file:
      - .env.example
    ports:
      - "8080:8080"

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Seoul
    ports:
      - "127.0.0.1:5432:5432"
