version: "3.9"

services:
  mock_server:
    build:
      context: mock_server
    ports:
      - "5000:5000"

  frontend:
    build:
      context: frontend
      args:
        - VITE_API_BASE_URL=http://localhost:5000/api/1
    ports:
      - "3000:80"