services:
  frontend:
    build:
      context: frontend
    ports:
      - "8100:80"

  backend:
    build:
      context: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: learning_assistant_db
      DB_USER: user
      DB_PASSWORD: password
      ADMIN_LOGIN_PASSWORD: password
      CORS_ORIGIN: http://localhost:8100
      GOOGLE_API_KEY: key
    ports:
      - "8080:8080"

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: learning_assistant_db
      TZ: Asia/Seoul
    ports:
      - "127.0.0.1:5432:5432"