version: "3.9"

services:
  frontend:
    build:
      context: frontend
    ports:
      - "8100:80"

  backend:
    build:
      context: .
    environment:
      DB_HOST: db
      ADMIN_LOGIN_PASSWORD: password
    ports:
      - "8200:8080"

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: learning_assistant_db
      TZ: Asia/Seoul
    ports:
      - "127.0.0.1:5432:5432"