spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:learning_assistant_db}"
    username: "${DB_USER:user}"
    password: "${DB_PASSWORD:password}"
    driver-class-name: org.postgresql.Driver

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true

  application:
    name: learning-assistant

  profiles:
    active: dev

logging:
  level:
    org.hibernate.SQL: debug

llm:
  google:
    base_url: "${GOOGLE_BASE_URL:https://generativelanguage.googleapis.com}"
    api_key: "${GOOGLE_API_KEY:key}"
    model: "${GOOGLE_MODEL:gemini-2.5-flash-preview-04-17}"

cors_origin: "${CORS_ORIGIN:http://localhost:8100}"

translation:
  prediction_count: "${TRANSLATION_PREDICTION_COUNT:2}"

admin:
  login:
    password: ${ADMIN_LOGIN_PASSWORD}